Check whether dpkg knows about the stray files.
git-svn-id: svn://svn.debian.org/pkg-nvidia/packages/nvidia-support/trunk@2306 b6a4b1ba-b714-0410-8a2d-fc0b36c6496e

diff --git a/check-for-conflicting-opengl-libraries b/check-for-conflicting-opengl-libraries
--- a/check-for-conflicting-opengl-libraries
+++ b/check-for-conflicting-opengl-libraries
@@ -32,6 +32,12 @@ for f in "$libdir"/$pattern "$libdir"/{i386,x86_64}-linux-gnu/$pattern
 do
 	if [ -e "$f" ] || [ -L "$f" ]
 	then
+		if dpkg-query -S "$f" >/dev/null 2>&1
+		then
+			echo "ERROR: The conflicting library '$f' is known to dpkg." >&2
+			dpkg-query -S "$f" >&2
+			exit 1
+		fi
 		CONFLICT_LIBS="$CONFLICT_LIBS $f"
 	fi
 done
