evaluate DPKG_MAINTSCRIPT_PACKAGE to look in /usr/lib or /usr/lib32
git-svn-id: svn://svn.debian.org/pkg-nvidia/packages/nvidia-common/trunk@1705 b6a4b1ba-b714-0410-8a2d-fc0b36c6496e

diff --git a/check-for-conflicting-opengl-libraries b/check-for-conflicting-opengl-libraries
--- a/check-for-conflicting-opengl-libraries
+++ b/check-for-conflicting-opengl-libraries
@@ -4,8 +4,24 @@ set -e
 
 . /usr/share/debconf/confmodule
 
+# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
+if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
+then
+	echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
+	exit 1
+fi
+
+case "$DPKG_MAINTSCRIPT_PACKAGE" in
+	*-ia32*)
+		libdir="/usr/lib32"
+		;;
+	*)
+		libdir="/usr/lib"
+		;;
+esac
+
 CONFLICT_LIBS=""
-for f in /usr/lib/libGL.so.*.*
+for f in "$libdir"/libGL.so.*.*
 do
 	if [ -e "$f" ] || [ -L "$f" ]
 	then
